apiVersion: v1
kind: Service
metadata:
  name: dustin-te-ds-svc
spec:
  type: NodePort
  selector:
    app: dustin-te-ds
  ports:
    - port: 49152
      name: "thousandeyes-1"
      targetPort: 49152
      nodePort: 32152
    - port: 49153
      name: "thousandeyes-2"
      targetPort: 49153
      nodePort: 32153
